export default {
    VARIAVEL: "VARIAVEL",
    NOME_VAR: "NOME_VAR",
    IGUAL: "IGUAL",
    PARENTESE_ESQUERDO: "PARENTESE_ESQUERDO",
    PARENTESE_DIREITO: "PARENTESE_DIREITO",
    CHAVE_ESQUERDA: "CHAVE_ESQUERDA",
    CHAVE_DIREITA: "CHAVE_DIREITA",
    MOSTRAR: "MOSTRAR",
    LEIA:"LEIA",
    PONTO_VIRGULA: "PONTO_VIRGULA",
    VIRGULA:"VIRGULA",
    NUMERO:"NUMERO",
    STRING: "STRING",
    MAIS: "MAIS",
    MENOS: "MENOS",
    MULTIPLICACAO: "MULTIPLICACAO",
    DIVISAO: "DIVISAO",
    NULL: "NULL",   
    EOF: "EOF",
};


    
